name: CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      
      - name: Prepare .env file
        run: cp .env.example .env
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Start FastAPI in background
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8090 > uvicorn.log 2>&1 &
          sleep 5

      - name: Run test app
        run: pytest -v


  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install linter
        run: pip install ruff

      - name: Run linter
        run: ruff check . || true